import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import NextUILayout from "@/app/NextUIProvider";
import NavbarComponent from "@/components/SiteComponents/Navbar/NavbarComponent";
import FooterComponent from "@/components/SiteComponents/Footer/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUILayout>
          <NavbarComponent/>
          {children}
          <FooterComponent/>
        </NextUILayout>
      </body>
    </html>
  );
}
